  env: "local" # local, dev, prod
  db_url: "postgres://postgres:Zaurbek@localhost:5434/mydb?sslmode=disable"
  http_server:
    address: "localhost:8080"
    timeout: 4s
    idle_timeout: 60s
    user: "myuser"
    password: "mypass"